# Generated by Django 2.0 on 2017-12-21 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_user_profiles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ['-priority']},
        ),
    ]
