# Generated by Django 2.0 on 2017-12-22 01:37

import allianceauth.authentication.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_auto_20171221_2023'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='characterownership',
            managers=[
                ('objects', allianceauth.authentication.managers.CharacterOwnershipManager()),
            ],
        ),
    ]
