# Generated by Django 2.0 on 2017-12-25 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_auto_20171222_0137'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='characterownership',
            managers=[
            ],
        ),
    ]
